<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Chat Anonyme</title>
  <link rel="stylesheet" href="src/public/css/app.css" />
</head>
<body>

  <header>
    <h1>Chat Anonyme</h1>
    <nav>
      <ul>
        <li><a href="index.php?page=about">À propos</a></li>
        <li><a href="index.php?page=room">Salons</a></li>
      </ul>
    </nav>
  </header>

  <main>
    <?php if(isset($_GET['message'])) : ?>
      <p><?= $_GET['message'] ?></p>
    <?php endif; ?>
    <?php include $template.'.phtml'; ?>
  </main>

</body>
</html>
